### ISSUE TITLE
Set PHP locale to current language when dealing with the dates

### ISSUE THREAD

**Issue by gsurrel** [real-or-random/dokuwiki-plugin-icalevents#10]
On a wiki not configured to English, the PHP locale may not be set according to the Wiki locale. Therefore, when using a strftime() call generating a string with the day names (and not numbers), it doesn't match the Wiki displayed language.

**Comment by real-or-random** [comment]
Thanks for the bug report. 
I'm not sure if I understand. As far as I know, there is no wiki locale. There's just a setting for "interface language".

I don't think it's a good idea to set the PHP locale. This is the responsibility of the administrator, and it would be very confusing if some plugin sets it. Also, it's not trivial to set it based on the interface language setting, because we would need a mapping from languages to locales, which even depends on the OS.

**Comment by gsurrel** [comment]
Maybe indeed it's not the right way to do it (or maybe simply saving the current locale, set temporary the locale to the interface language one, generate all the time strings required, and restore the original locale.

The problem is that for multilingual wikis (or simply wikis with a different locale than the system's one), the date strings "Saturday 3 November" will not match the wiki language "Samedi 3 novembre", "Sabado 3 de noviembre" which brings inconsistency and even confusion for non English speakers.

I tried to have embedded PHP code in my pages to programmatically change the PHP locale, but I just get the code verbatim with syntax highlight. Maybe I'm doing something wrong here, I am not sure (I understand it's much safer this way).

**Comment by real-or-random** [comment]
Hm, multilingual wikis are anyway not supported, right? (There's only one interface language.)

I think then the simplest solution (dokuwiki is intentionally designed to be very simple), is to use a date format which does not have to be localized, e.g., ISO: YYYY-MM-DD. (Weirdly, dokuwiki uses YYYY/MM/DD, which is not standardized at all.) That's not super beautiful but it works.

In your specific case:
Do you have raw access to the dokuwiki installation, i.e., can you edit the files? If yes, I would add the setting in  one of dokuwiki's config files. If not, I think the proper way to do this is to write a plugin, whose only purpose is to set the locale, because the problem itself is not specific to this plugin.  That's also less confusing for the admin, because it's more explicit.

**Comment by gsurrel** [comment]
OK, I'll do that because I indeed have access to the installation. I'll investigate the creation of a plugin as it could be useful for others too. Thanks!
