### ISSUE TITLE
Consider recurrent events

### ISSUE THREAD

**Issue by gsurrel** [real-or-random/dokuwiki-plugin-icalevents#11]
The plugin doesn't handle properly recurrent events. Here is an example you can try easily, with both the Google rendering and text view by the plugin for easy comparison :

```
{{iCalEvents>https://calendar.google.com/calendar/ical/2lmeg74hmnd78fqns881nl05rg%40group.calendar.google.com/public/basic.ics#from=today}}
<html>
<iframe src="https://calendar.google.com/calendar/embed?src=2lmeg74hmnd78fqns881nl05rg%40group.calendar.google.com&ctz=Europe/Paris" style="width:800px;height:500px;"/>
</html>
```

Roughly, the cases are those ones:

* Test 1 defined for a given number of repetition
* Test 2 defined until a date
* Test 3 defined as "1st wednesday of the month"

**Comment by real-or-random** [comment]
Yes, the plugin should handle recurrent events. The iCalcreator library actually supports them but in a weird manner, that's why it does not work at the moment. This may be a good reason to switch to sabre, another iCalendar library, see #4. It handles recurrent events much more naturally, see http://sabre.io/vobject/recurrence/ .

 I can look into that but probably not quickly. Pull requests are always welcome of course.

**Comment by viisauksena** [comment]
+1 add me - would be awesome, alsoit becomes tricky when displaying the next upcoming events
