### ISSUE TITLE
evaluate sabre-vobject

### ISSUE THREAD

**Issue by glensc** [real-or-random/dokuwiki-plugin-icalevents#4]
i came across to this library when investigating what is the `iCalcreator` library being used: https://github.com/fruux/sabre-vobject

few benefits i see:
- [composer](https://github.com/fruux/sabre-vobject#installation) compatible
- [active](https://github.com/fruux/sabre-vobject/pulse/monthly) development
- [versioned](https://github.com/iCalcreator/iCalcreator/issues/21) tags
- [php7](https://github.com/iCalcreator/iCalcreator/issues/25) compatible

altho latest version [requires php 5.5](https://github.com/fruux/sabre-vobject/blob/4.1.1/composer.json#L35) might be an issue considering dokuwiki itself requires php 5.3 as minimum version

but there's older 3.5 series which requires just [php 5.3](https://github.com/fruux/sabre-vobject/blob/3.5/composer.json#L8)

if you see the library fit, i see the integration as:
- create `composer.json`: `composer require sabre/vobject "^3.5"`
- add it to version control: `git add composer.json && git commit -a`
- install deps: `composer install`
- `require vendor/autoload.php` to initialize deps in code
- include `vendor/*` in release `.zip`

i actually use such method in [eventum](https://github.com/eventum/dokuwiki-plugin-eventum/) plugin. have look at the project `Makefile` of the zip build process

**Comment by real-or-random** [comment]
Yes, thanks for the hint. I looked at all several libraries including this one.
I cannot remember exactly why I didn't use sabre. I think the reason was that [iCalcreator](/iCalcreator/iCalcreator) seemed more lightweight. It works pretty well actually and it works in PHP7 (just E_DEPRECATED).

I think sabre is an option to keep in mind for the future but there is no reason to switch at the moment. Also development is not entirely dead in iCalcreator.

**Comment by real-or-random** [comment]
I've created branch 'sabre' for this. In progress.
