### ISSUE TITLE
dformat support lost

### ISSUE THREAD

**Issue by glensc** [real-or-random/dokuwiki-plugin-icalevents#6]
there was `dformat` support in older version that was respected from event parameters:

```

{{iCalEvents>https://www.google.com/calendar/ical/..../basic.ics#from=2 month ago&showEndDates=1&showCurrentWeek=1&dformat=%Y-%m-%d %H:%M:%S <b>(%V)</b>}}
```

this seems no longer have effect with 2016-08-17 release.

note: yes, it's configurable globally, but i used to configure it per instance to have different look

**Comment by glensc** [comment]
it was added in [2.0.1](https://www.dokuwiki.org/plugin:icalevents#version_history) release: 
- showEndDates, dformat configurable via wiki page as well, not only config

**Comment by real-or-random** [comment]
I tried to keep almost all of the functionality but yes, I overlooked that. I can add this back.

**Comment by glensc** [comment]
thanks. looking forward!

**Comment by real-or-random** [comment]
Now there is dformat and tformat (separately). Separation is necessary  for showEndDates support.
However, the `<b>%V</b>` won't work because htmlspecialchars is applied for security reasons. Do you need this?
(A proper solution would be support {date} and {time} separately in the template I think. But that also would not be enough to have only the `%V` in bold.)

**Comment by glensc** [comment]
i can likely live without `<b>`, however i think `dformat` and `tformat` are not supported as parameters?

**Comment by real-or-random** [comment]
I introduced it in the commit one hour ago, referenced here. Did you see that one?

**Comment by glensc** [comment]
did see now.
